[workspace]
resolver = "2"

members = [
    "bottlerocket-settings-sdk",
    "bottlerocket-template-helper",
    "bottlerocket-defaults-helper",
    "bottlerocket-settings-plugin",
    "bottlerocket-settings-derive",
]
