[services.docker]
restart-commands = ["/bin/systemctl try-restart docker.service"]
configuration-files = ["docker-daemon-config", "proxy-env"]

[configuration-files.docker-daemon-config]
path = "/etc/docker/daemon.json"
template-path = "/usr/share/templates/docker-daemon-json"

# Image registries
[metadata.settings.container-registry]
affected-services = ["docker", "host-containers", "bootstrap-containers"]
