[settings.kubernetes]
cluster-domain = "cluster.local"
standalone-mode = false
authentication-mode = "aws"
server-tls-bootstrap = true
cloud-provider = "aws"

[metadata.settings.kubernetes]
affected-services = ["kubernetes"]

[metadata.settings.kubernetes.pod-infra-container-image]
affected-services = ["pod-infra-container-image"]

[services.pod-infra-container-image]
configuration-files = ["pod-infra-container-image-log-message"]
restart-commands = ["systemctl restart deprecation-warning@pod-infra-container-image.timer"]

[configuration-files.pod-infra-container-image-log-message]
path = "/etc/deprecated-settings/pod-infra-container-image"
template-path = "/usr/share/templates/pod-infra-container-image"

[settings.metrics]
service-checks = ["apiserver", "chronyd", "containerd", "host-containerd", "kubelet"]

[metadata.settings.network]
affected-services = ["containerd", "kubernetes", "host-containerd", "host-containers", "updog"]

[services.autoscaling-warm-pool]
configuration-files = ["warm-pool-wait-toml"]
restart-commands = []

[configuration-files.warm-pool-wait-toml]
path = "/etc/warm-pool-wait.toml"
template-path = "/usr/share/templates/warm-pool-wait-toml"

[metadata.settings.autoscaling]
affected-services = ["autoscaling-warm-pool"]
