name: Rust
on:
  pull_request:
    branches: "*"
    paths-ignore:
      - '**.md'
      - 'COPYRIGHT'
      - 'LICENSE**'

  push:
    branches: [develop]
    paths-ignore:
      - '**.md'
      - 'COPYRIGHT'
      - 'LICENSE**'

jobs:
  build:
    runs-on:
      group: bottlerocket
      labels: bottlerocket_ubuntu-latest_8-core
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: cargo install cargo-deny
      - run: make build
